function signature = dtm2020BuildSignature()
%DTM2020BUILDSIGNATURE Inputs that invalidate a previously built native backend.
root = projectRoot();
files = ["src/native/dtm2020/dtm2020_bridge.f90", ...
    "src/native/dtm2020/dtm2020_bridge.h", ...
    "src/native/dtm2020/dtm2020_mex.c", "src/native/dtm2020/dtm2020_sfun.c", ...
    "tools/native/buildDtm2020Native.m", ...
    "third_party/dtm2020/upstream/src/libswamif/dtm2020_F107_Kp-subr_MCM.f90", ...
    "third_party/dtm2020/upstream/src/libswamif/dtm2020_sigma_function.f90", ...
    "third_party/dtm2020/upstream/data/DTM_2020_F107_Kp.dat"];
hashes = strings(size(files));
for k = 1:numel(files)
    hashes(k) = aocsFileHash(fullfile(root, files(k)));
end
signature = struct("Release", version('-release'), "Architecture", computer('arch'), ...
    "Files", files, "SHA256", hashes);
end
