classdef SolarRadiationPressureTest < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addEnvironmentPath(~)
            % Description:
            %   Adds source and test helper paths required by SRP tests.
            %
            % Arguments:
            %   None.
            %
            % Outputs:
            %   None.

            rootDirectory = fileparts(fileparts(fileparts(mfilename("fullpath"))));
            addpath(rootDirectory);
            setupAocsPaths(rootDirectory, true);
        end
    end

    methods (Test)
        function forcePressureAndTorqueFollowSunDirection(testCase)
            % Description:
            %   Verifies SRP pressure, body-frame force direction, and torque
            %   generated by a fixed center-of-pressure offset.
            %
            % Arguments:
            %   testCase - matlab.unittest.TestCase instance.
            %
            % Outputs:
            %   None.

            solarFlux_W_m2 = 1361.0;
            speedOfLight_m_s = 299792458.0;
            area_m2 = 0.03;
            reflectivity = 1.3;
            centerOfPressure_B_m = [0.0; 0.0; 0.05];

            [momentBody, forceBody, pressure] = computeSrpTorque( ...
                [1.0; 0.0; 0.0], solarFlux_W_m2, 1.0, area_m2, ...
                reflectivity, centerOfPressure_B_m);

            expectedPressure = solarFlux_W_m2 / speedOfLight_m_s;
            expectedForce = [-expectedPressure * reflectivity * area_m2; 0.0; 0.0];

            testCase.verifyEqual(pressure, expectedPressure, "RelTol", 1e-15);
            testCase.verifyEqual(forceBody, expectedForce, "RelTol", 1e-15, "AbsTol", 1e-20);
            testCase.verifyEqual(momentBody, cross(centerOfPressure_B_m, expectedForce), ...
                "RelTol", 1e-15, "AbsTol", 1e-20);
        end

        function accelerationUsesBodyToInertialTransform(testCase)
            % Description:
            %   Verifies that SRP acceleration uses the same body-to-inertial
            %   DCM convention as the aerodynamic coupling.
            %
            % Arguments:
            %   testCase - matlab.unittest.TestCase instance.
            %
            % Outputs:
            %   None.

            angle = pi / 2.0;
            C_BI = [cos(angle), sin(angle), 0.0; ...
                -sin(angle), cos(angle), 0.0; 0.0, 0.0, 1.0];
            forceBody_N = [-1.0e-7; 2.0e-8; 0.0];
            mass_kg = 4.0;

            [forceInertial_N, accelerationInertial_m_s2] = ...
                computeSrpAcceleration(forceBody_N, C_BI, mass_kg);

            testCase.verifyEqual(forceInertial_N, C_BI.' * forceBody_N, "AbsTol", 1e-20);
            testCase.verifyEqual(accelerationInertial_m_s2, forceInertial_N / mass_kg, ...
                "AbsTol", 1e-20);
        end

        function disabledModelReturnsZeroProducts(testCase)
            % Description:
            %   Verifies that disabling SRP zeros torque, force, and pressure.
            %
            % Arguments:
            %   testCase - matlab.unittest.TestCase instance.
            %
            % Outputs:
            %   None.

            [momentBody, forceBody, pressure] = computeSrpTorque( ...
                [1.0; 0.0; 0.0], 1361.0, 0.0, 0.03, 1.3, [0.0; 0.0; 0.05]);

            testCase.verifyEqual(momentBody, zeros(3, 1));
            testCase.verifyEqual(forceBody, zeros(3, 1));
            testCase.verifyEqual(pressure, 0.0);
        end

        function srpAndDisturbanceBusesPublishTranslationalProducts(testCase)
            % Description:
            %   Verifies that SRP and disturbance buses expose translational
            %   SRP products and the total orbit-perturbation acceleration.
            %
            % Arguments:
            %   testCase - matlab.unittest.TestCase instance.
            %
            % Outputs:
            %   None.

            srpBus = createAocsSrpBus();
            disturbanceBus = createAocsDisturbanceBus();
            disturbanceNames = string({disturbanceBus.Elements.Name});

            testCase.verifyEqual(string({srpBus.Elements.Name}), ...
                ["M_srp_B_Nm", "F_srp_B_N", "P_srp_N_m2"]);
            testCase.verifyTrue(any(disturbanceNames == "F_srp_B_N"));
            testCase.verifyTrue(any(disturbanceNames == "F_srp_I_N"));
            testCase.verifyTrue(any(disturbanceNames == "a_srp_I_m_s2"));
            testCase.verifyTrue(any(disturbanceNames == "a_dist_I_m_s2"));
        end
    end
end
