function ReferenceVectorBus = createReferenceVectorBus(targetWorkspace)
% Description:
%   Defines inertial reference vectors generated by onboard models.
%
% Arguments:
%   targetWorkspace - Optional workspace selector. Use "base" to assign the
%                     bus object to the MATLAB base workspace.
%
% Outputs:
%   ReferenceVectorBus - Simulink.Bus object for onboard reference vectors.

if nargin < 1
    targetWorkspace = "base";
end
targetWorkspace = string(targetWorkspace);

elems(1) = busElement("sun_I_unit", [3 1], "double", "1", ...
    "Onboard Sun direction expressed in inertial axes");
elems(2) = busElement("B_I_T", [3 1], "double", "T", ...
    "Onboard geomagnetic reference vector expressed in inertial axes");
elems(3) = busElement("valid", 1, "double", "1", ...
    "Reference-vector validity flag");
elems(4) = busElement("sgp4_update_time_s", 1, "double", "s", ...
    "Onboard time of the SGP4 state represented by the reference vectors");
elems(5) = busElement("sgp4_sequence_id", 1, "uint32", "1", ...
    "Discrete SGP4 update sequence represented by the reference vectors");

ReferenceVectorBus = Simulink.Bus;
ReferenceVectorBus.Description = "Onboard inertial reference vectors";
ReferenceVectorBus.Elements = elems;

if targetWorkspace == "base"
    assignin("base", "ReferenceVectorBus", ReferenceVectorBus);
end
end

function elem = busElement(name, dimensions, dataType, unit, description)
elem = Simulink.BusElement;
elem.Name = name;
elem.Dimensions = dimensions;
elem.DataType = dataType;
elem.Unit = unit;
elem.Description = description;
end
