function applySunEphemerisSettings(modelName, AOCS)
% Description:
%   Finds Planetary Ephemeris blocks and configures the project Sun vector
%   source from environment.sun.
%
% Arguments:
%   modelName - Loaded Simulink model name.
%   AOCS - Validated configuration struct.
%
% Outputs:
%   None.

sun = AOCS.Environment.Sun;
if sun.Model ~= "planet_ephemeris"
    error("AOCS:Simulink:UnsupportedSunModel", ...
        "Unsupported Sun model '%s'.", char(sun.Model));
end

blocks = findBlocksByBlockType(modelName, "PlanetaryEphem");
if isempty(blocks)
    error("AOCS:Simulink:MissingPlanetaryEphemeris", ...
        "environment.sun.model is 'planet_ephemeris', but no Planetary Ephemeris block was found in model '%s'.", ...
        char(modelName));
end

for k = 1:numel(blocks)
    set_param(blocks{k}, ...
        "units", "m,m/s", ...
        "epochFormat", "Julian date", ...
        "ephemerisModel", char(sun.EphemerisModel), ...
        "center", "Earth", ...
        "target", "Sun", ...
        "useDateRange", onOff(sun.UseEphemerisDateRange), ...
        "startDate", julianDateExpression(sun.EphemerisStartUtc), ...
        "endDate", julianDateExpression(sun.EphemerisEndUtc), ...
        "action", char(sun.Action), ...
        "outputVelocity", "off");
end
end
