function simIn = applyOrbitPropagatorSettings(modelName, AOCS, simIn)
% Description:
%   Finds Orbit Propagator blocks and binds the initial orbit plus selected
%   propagator model to AOCS_OrbitConfig and AOCS.Orbit.Propagator fields.
%
% Arguments:
%   modelName - Loaded Simulink model name.
%   AOCS - Validated configuration struct.
%
% Outputs:
%   None.

blocks = find_system(modelName, ...
    "LookUnderMasks", "all", ...
    "FollowLinks", "on", ...
    "BlockType", "OrbitPropagator");
if isempty(blocks)
    error("AOCS:Simulink:MissingRequiredBlock", "Missing OrbitPropagator block in %s.", modelName);
end

propagator = AOCS.Orbit.Propagator;

for k = 1:numel(blocks)
    simIn = setAocsParameters(simIn, blocks{k}, ...
        "propagator", char(propagator.MaskPropagator), ...
        "timeFormat", "Gregorian date", ...
        "startDate", "AOCS_OrbitConfig.epoch_utc", ...
        "dateOut", "on", ...
        "centralBody", char(AOCS.Orbit.CentralBody), ...
        "units", "Metric (m/s)", ...
        "angleUnits", "Radians");

    simIn = applyInitialOrbitStateSettings(blocks{k}, propagator, AOCS.Orbit.InitialState, simIn);

    if propagator.Type == "numerical_high_precision"
        simIn = applyHighPrecisionOrbitPropagatorSettings(blocks{k}, propagator, AOCS, simIn);
    end
end
end

function simIn = applyInitialOrbitStateSettings(block, propagator, initialState, simIn)
% Description:
%   Applies the selected initial-state representation to one Orbit Propagator
%   block mask.
%
% Arguments:
%   block - Orbit Propagator block path.
%   propagator - Normalized propagator configuration struct.
%   initialState - Normalized initial-state configuration struct.
%
% Outputs:
%   None.

switch initialState.Type
    case "keplerian"
        simIn = setAocsParameters(simIn, block, ...
            char(propagator.StateFormatParameter), "Orbital elements", ...
            "orbitType", "Keplerian", ...
            "semiMajorAxis", "AOCS_OrbitConfig.semi_major_axis_m", ...
            "eccentricity", "AOCS_OrbitConfig.eccentricity", ...
            "inclination", "AOCS_OrbitConfig.inclination_rad", ...
            "raan", "AOCS_OrbitConfig.raan_rad", ...
            "argPeriapsis", "AOCS_OrbitConfig.argument_of_periapsis_rad", ...
            "trueAnomaly", "AOCS_OrbitConfig.true_anomaly_rad");

    case "cartesian"
        simIn = setAocsParameters(simIn, block, ...
            char(propagator.StateFormatParameter), "ICRF state vector", ...
            "inertialPosition", "AOCS_OrbitConfig.r_I_m", ...
            "inertialVelocity", "AOCS_OrbitConfig.v_I_m_s");
end
end

function simIn = applyHighPrecisionOrbitPropagatorSettings(block, propagator, AOCS, simIn)
% Description:
%   Applies mask parameters used only by Aerospace Blockset high precision propagation.

simIn = setAocsParameters(simIn, block, ...
    "outportFrame", char(propagator.OutputFrame), ...
    "gravityModel", char(propagator.GravityModel), ...
    "useEOPs", onOff(propagator.UseEOPs), ...
    "action", "None", ...
    "accelIn", "on", ...
    "accelFrame", "ICRF", ...
    "useDrag", "off", ...
    "useSRP", "off", ...
    "ephemerisModel", char(AOCS.Environment.Sun.EphemerisModel), ...
    "useEphemerisDateRange", onOff(AOCS.Environment.Sun.UseEphemerisDateRange), ...
    "ephemerisStartDate", gregorianDateVectorExpression( ...
        AOCS.Environment.Sun.EphemerisStartUtc), ...
    "ephemerisEndDate", gregorianDateVectorExpression( ...
        AOCS.Environment.Sun.EphemerisEndUtc), ...
    "useThirdBodyGravity", onOff(propagator.UseThirdBodyGravity), ...
    "includeSunGravity", "on", ...
    "includeMoonGravity", "on");

if propagator.GravityModel == "Spherical harmonics"
    simIn = setAocsParameters(simIn, block, ...
        "earthSH", char(propagator.EarthSphericalHarmonics), ...
        "shDegree", numericString(propagator.SphericalHarmonicsDegree), ...
        "eopFile", char(propagator.EOPFile));
end
end
