function applyEarthFrameSettings(modelName, AOCS)
% Description:
%   Applies epoch and reduction settings to ECI/ECEF/LLA frame transform blocks.
%
% Arguments:
%   modelName - Loaded Simulink model name.
%   AOCS - Validated configuration struct.
%
% Outputs:
%   None.

applyEciToLlaSettings(modelName, AOCS);
applyEciToEcefDcmSettings(modelName, AOCS);
end

function applyEciToLlaSettings(modelName, AOCS)
% Description:
%   Finds ECI Position to LLA blocks and applies the JSON epoch as mask date
%   plus a seconds time-increment port.

blocks = find_system(modelName, ...
    "LookUnderMasks", "all", ...
    "FollowLinks", "on", ...
    "MaskType", "ECItoLLA");

epoch = AOCS.Epoch.Utc;
monthName = monthNumberToName(epoch(2));

for k = 1:numel(blocks)
    set_param(blocks{k}, ...
        "red", "IAU-2000/2006", ...
        "year", integerString(epoch(1)), ...
        "month", monthName, ...
        "day", integerString(epoch(3)), ...
        "hour", integerString(epoch(4)), ...
        "min", integerString(epoch(5)), ...
        "sec", numericString(epoch(6)), ...
        "deltaT", "Sec", ...
        "errorflag", "Error", ...
        "extraparamflag", "on", ...
        "eunits", "Metric (MKS)", ...
        "earthmodel", "WGS84");
end
end

function applyEciToEcefDcmSettings(modelName, AOCS)
% Description:
%   Finds standalone Direction Cosine Matrix ECI to ECEF blocks and applies
%   the JSON epoch as mask date plus a seconds time-increment port.

blocks = find_system(modelName, ...
    "LookUnderMasks", "all", ...
    "FollowLinks", "on", ...
    "MaskType", "DCMECItoECEF");

epoch = AOCS.Epoch.Utc;
monthName = monthNumberToName(epoch(2));

for k = 1:numel(blocks)
    if isWithinMaskedSubsystem(blocks{k}, "ECItoLLA")
        continue;
    end

    set_param(blocks{k}, ...
        "red", "IAU-2000/2006", ...
        "year", integerString(epoch(1)), ...
        "month", monthName, ...
        "day", integerString(epoch(3)), ...
        "hour", integerString(epoch(4)), ...
        "min", integerString(epoch(5)), ...
        "sec", numericString(epoch(6)), ...
        "deltaT", "Sec", ...
        "errorflag", "Error", ...
        "extraparamflag", "on");
end
end
