function applyEclipseShadowModelSettings(modelName, AOCS)
% Description:
%   Finds Aerospace Blockset Eclipse Shadow Model blocks and applies the
%   project eclipse settings from environment.eclipse.
%
% Arguments:
%   modelName - Loaded Simulink model name.
%   AOCS - Validated configuration struct.
%
% Outputs:
%   None.

eclipse = AOCS.Environment.Eclipse;
blocks = findBlocksByBlockType(modelName, "EclipseShadowModel");
if isempty(blocks)
    if ~eclipse.Enabled
        return;
    end

    error("AOCS:Simulink:MissingEclipseShadowModel", ...
        "environment.eclipse.enabled is true, but no Eclipse Shadow Model block was found in model '%s'.", ...
        char(modelName));
end

for k = 1:numel(blocks)
    set_param(blocks{k}, ...
        "units", "Metric (m)", ...
        "shadowModel", eclipseShadowModelMaskValue(eclipse.Model), ...
        "outputShadowRegion", onOff(eclipse.OutputShadowRegion), ...
        "timeSource", eclipseTimeSourceMaskValue(eclipse.TimeSource), ...
        "startDate", julianDateExpression(AOCS.Epoch.Utc), ...
        "centralBody", char(eclipse.CentralBody), ...
        "includeMoon", onOff(eclipse.IncludeMoon), ...
        "includeEarth", onOff(eclipse.IncludeEarth), ...
        "customRadius", numericString(AOCS.Orbit.CentralBodyConstants.radius_m), ...
        "ephemerisModel", char(eclipse.EphemerisModel), ...
        "useEphemerisDateRange", onOff(eclipse.UseEphemerisDateRange), ...
        "ephemerisStartDate", julianDateExpression(eclipse.EphemerisStartUtc), ...
        "ephemerisEndDate", julianDateExpression(eclipse.EphemerisEndUtc), ...
        "action", char(eclipse.Action), ...
        "zeroCrossing", onOff(eclipse.ZeroCrossing));
end
end
