function referenceFile = generateSinglePlateSentmanReference(adbsatRoot)
%GENERATESINGLEPLATESENTMANREFERENCE Build an independent Sentman fixture.
%   The generator calls ADBSat's coeff_sentman implementation. ADBSat is a
%   generation-time dependency only; the committed CSV is used by tests.

arguments
    adbsatRoot (1, 1) string
end

coefficientDirectory = fullfile(adbsatRoot, "toolbox", "fmf_eq");
if ~isfile(fullfile(coefficientDirectory, "coeff_sentman.m"))
    error("AOCS:Validation:MissingADBSat", ...
        "ADBSat coeff_sentman.m was not found under %s.", coefficientDirectory);
end

addpath(coefficientDirectory);
cleanup = onCleanup(@() rmpath(coefficientDirectory));

projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
referenceFile = fullfile(projectRoot, "validation", "aerodynamics", ...
    "data", "sentman_single_plate_reference.csv");

rows = repmat(emptyRow(), 0, 1);
baselineAnglesDeg = [0, 15, 30, 45, 60, 75, 85, 89, 90, 91, 135, 180];
for angleDeg = baselineAnglesDeg
    rows(end + 1) = referenceRow( ...
        sprintf("oxygen_angle_%02d", angleDeg), angleDeg, 7600.0, ...
        1.0e-12, 900.0, 300.0, 0.9, 0.03, 3.71565, ...
        [1, 0, 0, 0, 0, 0]); %#ok<AGROW>
end

speciesNames = ["O", "N2", "O2", "He", "H", "N"];
for speciesIndex = 1:6
    massFractions = zeros(1, 6);
    massFractions(speciesIndex) = 1.0;
    for angleDeg = [0, 45, 75]
        rows(end + 1) = referenceRow( ...
            sprintf("species_%s_angle_%02d", speciesNames(speciesIndex), angleDeg), ...
            angleDeg, 7600.0, 1.0e-12, 900.0, 300.0, 0.9, ...
            0.03, 3.71565, massFractions); %#ok<AGROW>
    end
end

for speedMps = [1000.0, 4000.0, 7600.0, 10000.0]
    for angleDeg = [0, 45, 75]
        rows(end + 1) = referenceRow( ...
            sprintf("speed_%05d_angle_%02d", speedMps, angleDeg), ...
            angleDeg, speedMps, 1.0e-12, 900.0, 300.0, 0.9, ...
            0.03, 3.71565, [1, 0, 0, 0, 0, 0]); %#ok<AGROW>
    end
end

for alpha = [0.0, 0.5, 0.9, 1.0]
    for wallTemperatureK = [200.0, 300.0, 600.0]
        for angleDeg = [0, 45, 75]
            rows(end + 1) = referenceRow( ...
                sprintf("surface_a%03d_tw%03d_angle_%02d", ...
                round(100 * alpha), round(wallTemperatureK), angleDeg), ...
                angleDeg, 7600.0, 1.0e-12, 900.0, wallTemperatureK, ...
                alpha, 0.03, 3.71565, [1, 0, 0, 0, 0, 0]); %#ok<AGROW>
        end
    end
end

representativeMassFractions = [0.70, 0.12, 0.03, 0.10, 0.03, 0.02];
for angleDeg = [0, 30, 60, 85]
    rows(end + 1) = referenceRow( ...
        sprintf("mixture_angle_%02d", angleDeg), angleDeg, 7600.0, ...
        1.0e-12, 900.0, 300.0, 0.9, 0.03, 3.71565, ...
        representativeMassFractions); %#ok<AGROW>
end

reference = struct2table(rows);
writetable(reference, referenceFile);
fprintf("Wrote %d ADBSat Sentman reference cases to %s.\n", ...
    height(reference), referenceFile);
end

function row = referenceRow(caseId, angleDeg, speedMps, rhoKgM3, ...
        atmosphereTemperatureK, wallTemperatureK, alpha, areaM2, ...
        spacecraftMassKg, massFractions)
atomicMassUnitKg = 1.66053906660e-27;
boltzmannJK = 1.380649e-23;
speciesMassKg = atomicMassUnitKg .* [16, 28, 32, 4, 1, 14];
massFractions = massFractions ./ sum(massFractions);
speedRatios = speedMps .* sqrt(speciesMassKg ./ ...
    (2.0 * boltzmannJK * atmosphereTemperatureK));

cp = 0.0;
ctau = 0.0;
for speciesIndex = 1:6
    if massFractions(speciesIndex) <= 0.0
        continue;
    end
    parameters = struct( ...
        "alpha", alpha, ...
        "s", speedRatios(speciesIndex), ...
        "Tw", wallTemperatureK, ...
        "Tinf", atmosphereTemperatureK);
    [speciesCp, speciesCtau] = coeff_sentman(parameters, deg2rad(angleDeg));
    cp = cp + massFractions(speciesIndex) * speciesCp;
    ctau = ctau + massFractions(speciesIndex) * speciesCtau;
end

qDynamicNm2 = 0.5 * rhoKgM3 * speedMps^2;
forceScaleN = qDynamicNm2 * areaM2;

row = emptyRow();
row.case_id = string(caseId);
row.angle_deg = angleDeg;
row.speed_m_s = speedMps;
row.rho_kg_m3 = rhoKgM3;
row.T_atm_K = atmosphereTemperatureK;
row.T_wall_K = wallTemperatureK;
row.alpha_E = alpha;
row.area_m2 = areaM2;
row.mass_kg = spacecraftMassKg;
row.mass_fraction_O = massFractions(1);
row.mass_fraction_N2 = massFractions(2);
row.mass_fraction_O2 = massFractions(3);
row.mass_fraction_He = massFractions(4);
row.mass_fraction_H = massFractions(5);
row.mass_fraction_N = massFractions(6);
row.cp_reference = cp;
row.ctau_reference = ctau;
row.force_x_reference_N = -forceScaleN * cp;
row.force_y_reference_N = forceScaleN * ctau;
row.force_z_reference_N = 0.0;
row.q_dynamic_reference_N_m2 = qDynamicNm2;
end

function row = emptyRow()
row = struct( ...
    "case_id", "", ...
    "angle_deg", 0.0, ...
    "speed_m_s", 0.0, ...
    "rho_kg_m3", 0.0, ...
    "T_atm_K", 0.0, ...
    "T_wall_K", 0.0, ...
    "alpha_E", 0.0, ...
    "area_m2", 0.0, ...
    "mass_kg", 0.0, ...
    "mass_fraction_O", 0.0, ...
    "mass_fraction_N2", 0.0, ...
    "mass_fraction_O2", 0.0, ...
    "mass_fraction_He", 0.0, ...
    "mass_fraction_H", 0.0, ...
    "mass_fraction_N", 0.0, ...
    "cp_reference", 0.0, ...
    "ctau_reference", 0.0, ...
    "force_x_reference_N", 0.0, ...
    "force_y_reference_N", 0.0, ...
    "force_z_reference_N", 0.0, ...
    "q_dynamic_reference_N_m2", 0.0);
end
