function dataset = addEnvironmentContextInputs(dataset, AOCS, time_s)
% Description:
%   Adds flattened environment-context inputs to a Simulink Dataset.
%
% Arguments:
%   dataset - Simulink external-input Dataset to extend.
%   AOCS - Validated configuration struct.
%   time_s - Sample times [s].
%
% Outputs:
%   dataset - Dataset with EnvironmentContext_* input elements added.

sampleCount = numel(time_s);
epochUtc = AOCS.Epoch.Utc;
earthOrientation = AOCS.Environment.EarthOrientation;

epochDateTime = datetime( ...
    epochUtc(1), epochUtc(2), epochUtc(3), ...
    epochUtc(4), epochUtc(5), epochUtc(6), ...
    "TimeZone", "UTC");
sampleDateTime = epochDateTime + seconds(time_s);
utc = datevec(sampleDateTime);

decimalYear = decyear( ...
    utc(:, 1), utc(:, 2), utc(:, 3), ...
    utc(:, 4), utc(:, 5), utc(:, 6));

dataset = addHarnessInput(dataset, ...
    "EnvironmentContext_decimal_year", decimalYear, time_s);
dataset = addHarnessInput(dataset, ...
    "EnvironmentContext_mu_m3_s2", ...
    repmat(AOCS.Orbit.CentralBodyConstants.mu_m3_s2, sampleCount, 1), ...
    time_s);
dataset = addHarnessInput(dataset, ...
    "EnvironmentContext_epoch_utc", ...
    repmat(reshape(epochUtc, 6, 1), 1, 1, sampleCount), ...
    time_s);
dataset = addHarnessInput(dataset, ...
    "EnvironmentContext_t_s", time_s, time_s);
dataset = addHarnessInput(dataset, ...
    "EnvironmentContext_epoch_tdb_jd", ...
    repmat(AOCS.Epoch.TdbJulianDate, sampleCount, 1), time_s);
dataset = addHarnessInput(dataset, ...
    "EnvironmentContext_delta_at_s", ...
    repmat(earthOrientation.DeltaAT_s, sampleCount, 1), time_s);
dataset = addHarnessInput(dataset, ...
    "EnvironmentContext_delta_ut1_s", ...
    repmat(earthOrientation.DeltaUT1_s, sampleCount, 1), time_s);
dataset = addHarnessInput(dataset, ...
    "EnvironmentContext_polar_motion_rad", ...
    repmat(earthOrientation.PolarMotion_rad, sampleCount, 1), time_s);
dataset = addHarnessInput(dataset, ...
    "EnvironmentContext_d_cip_rad", ...
    repmat(earthOrientation.DCIP_rad, sampleCount, 1), time_s);
end
